### ISSUE TITLE
Tk dependency

### ISSUE THREAD

**Issue by glsscnnn** [CharlesAverill/satyrn#26]
Okay so basically default package of python doesn't support tkinter cause it's like deprecated or something:

![Screenshot from 2020-08-17 12-03-28](https://user-images.githubusercontent.com/20232318/90423266-c17fc280-e081-11ea-8d26-7ee80c70e878.png)

you're going to want to fix this problem with:

`sudo pacman -S tk`
`sudo apt-get install python-tk`

not entirely sure if this is a issue on other systems would recommend more testing.

**Comment by CharlesAverill** [comment]
Added a try/catch that exits on a TK ImportError in dce6c2cf76bcefcdb08310816fdc9ba031b9d935. Don't want to auto-install anything or mess around with the `platform` module, so I just linked to the TK installation page. Thank you!
